server:
  port: 8001
spring:
  application:
    name: batch-demo

  datasource:
    username: undefvar
    password: secret
    url: jdbc:postgresql://localhost:5435/demoDB
  flyway:
    locations: "classpath:db/migration"
    enabled: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
