server:
  port: 8001
spring:
  application:
    name: batch-demo
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  datasource:
    username: undefvar
    password: secret
    url: jdbc:postgresql://localhost:5435/demoDB
